[build]
  # The directory containing your application code
  base = "main.py"
  
  # Command to install dependencies and build the Flask app
  command = "pip install -r requirements.txt && python3 -m flask run --host=0.0.0.0"
  
  # Folder where the built site or application will be published to
  publish = "build"

[[redirects]]
  from = "/"
  to = "/predict"
  status = 200
  force = true

[[functions]]
  # Directory where the serverless functions are located
  directory = "netlify-functions"

  # Define the timeout for functions
  timeout = 10

[[headers]]
  for = "/"
  [headers.values]
  Cache-Control = "no-store"
